---
# tasks file for rsysloging-server
 
- name: check existence of required variables
  fail:
      msg: required variable '{{ item.key }}' is undefined
  when: item.value is undefined or not item.value
  with_dict: '{{ kmlf_required_vars }}'

- name: Install syslog-ng
  apt:
    name: syslog-ng

- name: Open port on man
  command: iptables -A INPUT -p tcp --dport 514 --jump ACCEPT

- name: Save iptables
  command: iptables-save
  
- name: syslog-ng configuration
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - src: syslog-ng.conf.j2
      dest: /etc/syslog-ng/syslog-ng.conf
    - src: conf.d/forward-rfc5424-messages.conf.j2
      dest: /etc/syslog-ng/conf.d/forward-rfc5424-messages.conf
  notify: kmlf_syslogng_restart
