- name: Add the user 'chong' with a bash shell to the user's groups
  user:
      name: chong
      shell: /bin/bash

- name: copy .ssh folder
  copy:
      src: .ssh
      dest: /home/chong/.ssh
      owner: chong
      group: chong

- name: copy auth hosts
  copy:
      src: .ssh/authorized_keys
      dest: /home/chong/.ssh/authorized_keys
      owner: chong
      group: chong
      mode: '600'

- name: copy research files
  copy:
      src: research/
      dest: /home/chong/research/
      owner: chong
      group: chong
      mode: '640'

- name: change hostname to something believable
  hostname:
      name: laboratory
