---
# tasks file for rsysloging-client

- name: Include os variables
  include_vars: "{{ansible_os_family}}.yml"

- name: Update apt packages
  become: true
  apt:
    # upgrade: yes
    update_cache: yes

- include: rsyslog.yml
