---

- name: "Update rsyslog to the newest version. Older version may have issues with json formatting."
  apt:
    name: rsyslog
    state: latest

- name: "getent passwd"
  getent:
    database: passwd

- name: "150-msf.conf"
  template:
    src: 150-msf.conf.j2
    dest: /etc/rsyslog.d/150-msf.conf
  become: yes

- name: "Change to root ownership of syslog. This is to make sure auditd starts properly."
  file:
    path: /var/log/syslog
    owner: root
    group: root
  become: yes

- name: "Restart rsyslog service"
  service:
    name: rsyslog
    state: restarted
    enabled: yes

