---
# Basic configuration of all defined devices

# Installation of common tools at all hosts
- name: Configuring hosts
  hosts: hosts
  become: yes
  roles:
    - hosts

# Installation and configuration of each host
- name: Configuring devices separately
  hosts: hosts
  become: yes
  tasks:
  - name: include role
    include_role:
      name: "{{ inventory_hostname }}"

# Enable logging
- hosts: attacker
  become: true
  tasks:
    - name: Set DNS server on attacker
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
    - name: Add apt signing key
      apt_key:
        url: https://archive.kali.org/archive-key.asc
        state: present

- hosts: attacker
  become: true
  roles:
      - chrony

- name: setup logging bash
  hosts:
    - attacker
    - server
    - client
  gather_facts: yes
  become: yes
  become_user: root
  vars:
    student_id: 0
    sandbox_name: secret-laboratory-local
    local_man_ip: 10.1.26.100
  roles:
    - role: sandbox-logging-forward
      slf_destination: '{{ hostvars["man"].ansible_host | default(local_man_ip) }}'
      slf_sandbox_id: "{{ kypo_global_sandbox_allocation_unit_id | default(student_id) }}"
      slf_sandbox_name: '{{ kypo_global_sandbox_name | default(sandbox_name) }}'
      slf_pool_id: '{{ kypo_global_pool_id | default(None) }}'
    - role: sandbox-logging-bash

- name: setup logging msf
  hosts:
    - attacker
  gather_facts: yes
  become: yes
  become_user: root
  roles:
    - role: sandbox-logging-msf

- hosts: man
  gather_facts: no
  become: true
  vars:
    central_syslog_ip: 78.128.251.179
  roles:
    - role: kypo-man-logging-forward
      kmlf_destination: '{{ kypo_global_head_ip | default(central_syslog_ip) }}'
  tasks:
    - name: Replace the version of syslog-ng on MAN
      replace:
        path: /etc/syslog-ng/syslog-ng.conf
        regexp: '28'
        replace: '19'
    - name: Restart the syslog-ng service
      service:
        name: syslog-ng
        state: restarted
        enabled: yes
