- src: git@gitlab.ics.muni.cz:muni-kypo-crp/useful-ansible-roles/kypo-sandbox-logging-bash.git
  scm: git

- src: git@gitlab.ics.muni.cz:muni-kypo-crp/useful-ansible-roles/kypo-sandbox-logging-msf.git
  scm: git

- src: git@gitlab.ics.muni.cz:muni-kypo-crp/useful-ansible-roles/kypo-sandbox-logging-forward.git
  scm: git
